/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viw;

import com.sun.xml.internal.ws.api.streaming.XMLStreamWriterFactory;
import controle.ItemVenda_controle;
import controle.NotaVenda_controle;
import controle.Produto_controle;
import controle.Usuario_controle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.ItemVenda_modelo;
import model.NotaVenda_modelo;
import model.Produto_modelo;

/**
 *
 * @author sulis
 */
public class Buscar_Notas extends javax.swing.JInternalFrame {

    private String codgonotaSelecionada = "";
    private ArrayList<NotaVenda_modelo> notas = new ArrayList<NotaVenda_modelo>();

    /**
     * Creates new form Buscar_Notas
     */
    public Buscar_Notas() {
        initComponents();
        this.notas = new NotaVenda_controle().listarnotas();
        System.out.println("tamanho:" + notas.size());
        DefaultTableModel tbm = (DefaultTableModel) jTNotasVenda.getModel();
        for (int i = 0; i < notas.size(); i++) {
            System.out.println(notas.get(i).getHoracad());

            tbm.addRow(new Object[]{notas.get(i).getCod_venda(), notas.get(i).getDatacad(), notas.get(i).getValor_total(), notas.get(i).getHoracad(), notas.get(i).getQuantidade(), notas.get(i).getFuncionaio_cod_funcionario()});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNostasTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        enCodigoNota = new javax.swing.JTextField();
        btPesquisarNota = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTNotasVenda = new javax.swing.JTable();
        lbVendasReaizadas = new javax.swing.JLabel();
        lbVendasReaizadas1 = new javax.swing.JLabel();
        lbDetalheVendas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtDetalheNota = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lbNostasTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNostasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNostasTitulo.setText("Notas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btPesquisarNota.setText("Buscar");
        btPesquisarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarNotaActionPerformed(evt);
            }
        });

        jTNotasVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Data", "Valor Total", "Hora", "Nº de Produtos", "Cod Funcionario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTNotasVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTNotasVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTNotasVenda);

        lbVendasReaizadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVendasReaizadas.setText("Vendas Reaizadas");

        lbVendasReaizadas1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVendasReaizadas1.setText("Digite o Codigo Da Venda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbVendasReaizadas1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enCodigoNota, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbVendasReaizadas))
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enCodigoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisarNota)
                    .addComponent(lbVendasReaizadas1))
                .addGap(16, 16, 16)
                .addComponent(lbVendasReaizadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        lbDetalheVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDetalheVendas.setText("Detalhes da venda");

        JtDetalheNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Produto", "Valor", "Quantidade", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JtDetalheNota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbDetalheVendas)
                        .addContainerGap(660, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNostasTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNostasTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDetalheVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarNotaActionPerformed
        // TODO add your handling code here:
        int cod_nota_busca = 0;
        try {
            cod_nota_busca = Integer.parseInt(enCodigoNota.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "codigo não numerico inserido");
        }

        DefaultTableModel tbm = (DefaultTableModel) jTNotasVenda.getModel();
        int nota = 0;
        for (int i = 0; i < notas.size(); i++) {
            if (notas.get(i).getCod_venda() == cod_nota_busca) {
                if (tbm.getRowCount() != 0) {

                    while (tbm.getRowCount() > 0) {
                        tbm.removeRow(0);

                    }
                    tbm.addRow(new Object[]{notas.get(i).getCod_venda(), notas.get(i).getData(), notas.get(i).getValor_total(), notas.get(i).getQuantidade(), notas.get(i).getFuncionaio_cod_funcionario()});
                } else {
                    JOptionPane.showMessageDialog(null, "Não existen nenhum registro de nota");
                }
                nota = notas.get(i).getCod_venda();
            } else {

            }
        }
        if (nota == 0) {
            for (int i = 0; i < notas.size(); i++) {
                System.out.println(notas.get(i).getHoracad());

                tbm.addRow(new Object[]{notas.get(i).getCod_venda(), notas.get(i).getDatacad(), notas.get(i).getValor_total(), notas.get(i).getHoracad(), notas.get(i).getQuantidade(), notas.get(i).getFuncionaio_cod_funcionario()});

            }
            JOptionPane.showMessageDialog(null, "Nota nãoexiste");
        }


    }//GEN-LAST:event_btPesquisarNotaActionPerformed

    private void jTNotasVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNotasVendaMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = 0;
        this.codgonotaSelecionada = source.getModel().getValueAt(row, column) + "";

        try {
            DefaultTableModel tbmDetalhe = (DefaultTableModel) JtDetalheNota.getModel();
            if (tbmDetalhe.getRowCount() > 0) {
                while (tbmDetalhe.getRowCount() > 0) {
                    tbmDetalhe.removeRow(0);

                }
                int cod = Integer.parseInt(codgonotaSelecionada);
                ArrayList<ItemVenda_modelo> itens = new ItemVenda_controle().buscar(cod);
                ArrayList<Produto_modelo> produtos = new Produto_controle().buscarprodutos();

                String nome_produto = "";
                for (int i = 0; i < itens.size(); i++) {
                    for (int a = 0; a < produtos.size(); a++) {

                        if (produtos.get(a).getCod_produto() == itens.get(i).getProduto_cod_produto()) {
                            nome_produto = produtos.get(a).getNome();
                            System.out.println("nome do pproduto "+itens.size()+"Qual ponto "+i + produtos.get(a).getNome()+"com codigo"+codgonotaSelecionada);
                        } else {

                        }

                    }
                    tbmDetalhe.addRow(new Object[]{itens.get(i).getCod_item_venda(), nome_produto, itens.get(i).getValor(), itens.get(i).getQuantidade(), itens.get(i).getValor_total()});

                }
            } else {
                int cod = Integer.parseInt(codgonotaSelecionada);
                ArrayList<ItemVenda_modelo> itens = new ItemVenda_controle().buscar(cod);
                ArrayList<Produto_modelo> produtos = new Produto_controle().buscarprodutos();

                String nome_produto = "";
                for (int i = 0; i < itens.size(); i++) {
                    for (int a = 0; a < produtos.size(); a++) {

                        if (produtos.get(a).getCod_produto() == itens.get(i).getProduto_cod_produto()) {
                            nome_produto = produtos.get(a).getNome();
                            System.out.println("nome do pproduto" + produtos.get(a).getNome());
                        } else {

                        }

                    }
                    System.out.println(itens.get(i).getValor());
                    tbmDetalhe.addRow(new Object[]{itens.get(i).getCod_item_venda(), nome_produto, itens.get(i).getValor(), itens.get(i).getQuantidade(), itens.get(i).getValor_total()});

                }
            }

        } catch (Exception e) {
            System.out.println("erro no detalhamento" + e);
        }


    }//GEN-LAST:event_jTNotasVendaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtDetalheNota;
    private javax.swing.JToggleButton btPesquisarNota;
    private javax.swing.JTextField enCodigoNota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTNotasVenda;
    private javax.swing.JLabel lbDetalheVendas;
    private javax.swing.JLabel lbNostasTitulo;
    private javax.swing.JLabel lbVendasReaizadas;
    private javax.swing.JLabel lbVendasReaizadas1;
    // End of variables declaration//GEN-END:variables
}
