/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viw;

//import Dao.ProdutoDao;
import controle.ItemVenda_controle;
import controle.NotaVenda_controle;
import javax.swing.table.DefaultTableModel;
import controle.Produto_controle;

import java.awt.CardLayout;
import java.beans.PropertyVetoException;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import controle.Usuario_controle;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JPasswordField;
import javax.swing.table.TableModel;
import model.ItemVenda_modelo;
import model.NotaVenda_modelo;
import model.Produto_modelo;
//import modelo.Produto;

/**
 * /**
 *
 * @author sulis
 */
public class TelaCaixaVenda extends javax.swing.JInternalFrame {

    ArrayList<Produto_modelo> produtos = new ArrayList<Produto_modelo>();
    private Random sorte = new Random();
    private int numeronota = 0;
    private int qtdt = 0;
    private int cod_usuario;

    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixaVenda(int cod_usuario) {
        initComponents();
        
        this.cod_usuario = cod_usuario;
        try {
            this.produtos = (new Produto_controle().buscarprodutos());
            for (int i = 0; i < this.produtos.size(); i++) {
                this.comboboxProduto.addItem(this.produtos.get(i).getNome());
            }
        } catch (Exception e) {
            System.out.println("erro na exibição dos produtos" + e);
        }
//         ArrayList<Produto> produtos = new ProdutoControle().buscarProduto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        enVl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbTroco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        root = new javax.swing.JPanel();
        ControleCaixa = new javax.swing.JPanel();
        lbCod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        ico = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbTroco1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        enValEn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbVt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboboxProduto = new javax.swing.JComboBox<>();
        envl = new javax.swing.JLabel();
        enQtd = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        JtProdutos = new javax.swing.JTable();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Valor");

        enVl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enVl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enVlActionPerformed(evt);
            }
        });
        enVl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enVlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enVlKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Troco");

        lbTroco.setBackground(new java.awt.Color(255, 255, 255));
        lbTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTroco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adicionar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton4.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setText("Finaliza");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("Cancelar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        setMinimumSize(new java.awt.Dimension(650, 531));
        setPreferredSize(new java.awt.Dimension(650, 531));

        root.setBackground(new java.awt.Color(255, 0, 0));
        root.setLayout(new java.awt.CardLayout());

        ControleCaixa.setBackground(new java.awt.Color(255, 255, 255));
        ControleCaixa.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        lbCod.setBackground(new java.awt.Color(255, 255, 255));
        lbCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCod.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Codigo do produto:");

        jToggleButton5.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setText("Finaliza");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton6.setText("Cancelar");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Troco");

        lbTroco1.setBackground(new java.awt.Color(255, 255, 255));
        lbTroco1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTroco1.setText("0");
        lbTroco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Adicionar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Calcular");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        enValEn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enValEn.setText("0");
        enValEn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enValEnMouseClicked(evt);
            }
        });
        enValEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enValEnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Produto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Dinheiro Entrada");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Quantidade");

        lbVt.setBackground(new java.awt.Color(255, 255, 255));
        lbVt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbVt.setText("0");
        lbVt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Valor Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Valor");

        comboboxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        comboboxProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboboxProdutoMouseClicked(evt);
            }
        });
        comboboxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxProdutoActionPerformed(evt);
            }
        });

        envl.setBackground(new java.awt.Color(255, 255, 255));
        envl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        envl.setText("0");
        envl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        enQtd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enQtd.setText("0");
        enQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enQtdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTroco1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(192, 192, 192))
                    .addComponent(lbVt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboboxProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(envl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enQtd)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enValEn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(envl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enValEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTroco1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "Produto", "Valor", "Quantidade", "vatol total unitario", "Remover"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtProdutosMouseClicked(evt);
            }
        });
        JtProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtProdutosKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(JtProdutos);

        javax.swing.GroupLayout ControleCaixaLayout = new javax.swing.GroupLayout(ControleCaixa);
        ControleCaixa.setLayout(ControleCaixaLayout);
        ControleCaixaLayout.setHorizontalGroup(
            ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControleCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControleCaixaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControleCaixaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControleCaixaLayout.createSequentialGroup()
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addComponent(ico)
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ControleCaixaLayout.setVerticalGroup(
            ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControleCaixaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControleCaixaLayout.createSequentialGroup()
                        .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControleCaixaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControleCaixaLayout.createSequentialGroup()
                                .addComponent(ico)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControleCaixaLayout.createSequentialGroup()
                                .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jToggleButton6)
                                    .addComponent(jToggleButton5))
                                .addContainerGap())))))
            .addGroup(ControleCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        root.add(ControleCaixa, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enVlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enVlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enVlActionPerformed

    private void enVlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enVlKeyPressed

    }//GEN-LAST:event_enVlKeyPressed

    private void enVlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enVlKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_enVlKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        DefaultTableModel dtmProduto = (DefaultTableModel) JtProdutos.getModel();
        Object[] dados = {lbCod.getText(), comboboxProduto.getSelectedItem(), enVl.getText(), enQtd.getText()};
        dtmProduto.addRow(dados);
        float v1 = Float.parseFloat(envl.getText());
        float v2 = (Float.parseFloat(lbVt.getText()));
        lbVt.setText("" + (v1 + v2));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        enQtd.setText("");
        enValEn.setText("");
        enVl.setText("");
        lbVt.setText("");
        comboboxProduto.setSelectedItem("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
//        try {
//            // TODO add your handling code here:
//            CaixaControle ca = new CaixaControle();
//            boolean result = ca.registrarVenda(Double.parseDouble(lbVt.getText()));
//            if(result == true){
//                JOptionPane.showMessageDialog(null, "inserção concluida");
//            }else{
//                JOptionPane.showMessageDialog(null, "falha na inserção");
//            }
//        } catch (SQLException ex) {
//            System.out.println(ex);
//        } catch (ParseException ex) {
//            Logger.getLogger(TelaCaixaVenda.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        JTextField username = new JTextField();
        JPasswordField password = new JPasswordField();
        Object[] message = {
            "Username:", username,
            "Password:", password
        };
        if (JtProdutos.getModel().getRowCount() != 0) {
            int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                Usuario_controle uc = new Usuario_controle();
                try {
                    lbVt.setText("0");
                    int user = Integer.parseInt(username.getText());
                    if (uc.efetuarLoginAdm(user, password.getText())) {
                        int rowf = JtProdutos.getRowCount();
                        int i = 1;
                        if (JtProdutos.getModel().getRowCount() > 0) {
                            while (JtProdutos.getModel().getRowCount() > 0) {
                                ((DefaultTableModel) JtProdutos.getModel()).removeRow(0);
                                ((DefaultTableModel) JtProdutos.getModel()).removeRow(0);
                            }
                        } else {
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Acesso negado");

                    }
                } catch (Exception e) {
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "nenhum item adicionado");
        }

    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        try {
            if (JtProdutos.getModel().getRowCount() != 0) {
                float vt = Float.parseFloat(lbVt.getText());
                LocalDateTime data = LocalDateTime.now();
                String datahora = data + "";
                

                String dataformatada = datahora.substring(0, 10);
                String horaformatada = datahora.substring(11, 19);
                System.out.println(dataformatada + " hora " + horaformatada);
                int qtd = Integer.parseInt(enQtd.getText());

//              INSERIND NOTA
                try {
                    float vt_insert = Float.parseFloat(lbVt.getText());
                    NotaVenda_modelo nota_modelo = new NotaVenda_modelo(this.cod_usuario, 0, 0, vt, datahora, datahora, horaformatada, this.qtdt, vt_insert);
                    this.numeronota = new NotaVenda_controle().inserirNotas(nota_modelo);
                    System.out.println("passou");
                } catch (Exception e) {
                    System.err.println("erro ao inserir a nota no bd na tela caixa no butão finalizar:" + e);
                }
                System.out.println(" abrinonota venda");

                NotaVenda_modelo notaob = new NotaVenda_modelo(cod_usuario, 0, numeronota, vt, dataformatada, dataformatada, horaformatada, this.qtdt, vt);
                if (numeronota != 0) {
                    this.setVisible(false);
                    Nota_Venda nota = new Nota_Venda(JtProdutos, notaob, 1);
                    nota.setVisible(true);

                } else {
                    Nota_Venda nota = new Nota_Venda(JtProdutos, notaob, 2);
                    nota.setVisible(true);

                }

//              CRIANDO O ITEM VENDA
                System.out.println(" iniciando itens");
                TableModel mdtb = JtProdutos.getModel();
                
                ArrayList<ItemVenda_modelo> itens = new ArrayList<ItemVenda_modelo>();
                try {
                    for (int i = 0; i < mdtb.getRowCount(); i++) {
                        ItemVenda_modelo item = new ItemVenda_modelo();
                        item.setProduto_cod_produto(Integer.parseInt(mdtb.getValueAt(i, 0) + ""));
                        item.setDatacad(dataformatada);
                        item.setHoracad(horaformatada);
                        item.setNotavenda_cod_venda(numeronota);
                        item.setValor(Float.parseFloat(mdtb.getValueAt(i, 2) + ""));
                        item.setQuantidade(Integer.parseInt(mdtb.getValueAt(i, 3) + ""));
                        item.setValor_total(Float.parseFloat(mdtb.getValueAt(i, 4) + ""));
                        itens.add(item);

                    }
                    boolean result = new ItemVenda_controle().salvaritens(itens, this.numeronota);
                    if (result == false) {
                        System.out.println("item venda inserido com sucesso");
                    } else {
                        System.out.println("inserção de item falhou");
                    }
                } catch (ArrayIndexOutOfBoundsException e) {
                    System.out.println("erro ao inserir item venda" + e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "não foi inserido nenhum item");
            }

        } catch (Exception e) {
            System.out.println("Erro ao abrir tela caixa" + e);
        }
        System.out.println("ok");
        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String entrada = enValEn.getText();
            String entradarefatorada = entrada.replaceAll(",", ".");
            float v1 = Float.parseFloat(lbVt.getText());
            float v2 = Float.parseFloat(entradarefatorada);
            if (v2 <= 0) {

            } else {
                float troco = v2 - v1;
                DecimalFormat formatadortroco = new DecimalFormat("0.00");
                lbTroco1.setText((formatadortroco.format(troco)) + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "cheque o valor de entrada ");
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void enValEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enValEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enValEnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        enQtd.setText("0");
        enValEn.setText("0");
        envl.setText("0");
        lbTroco1.setText("0");
        comboboxProduto.setSelectedItem("");


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        float v2 = Float.parseFloat(envl.getText());
        int qt = 0;
        try {
            qt = Integer.parseInt(enQtd.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A quantidade inserida deve ser um valor inteiro.");
        }

        this.qtdt += qt;
        if (((v2 != 0) && (qt != 0))) {
            try {
                float v1 = Float.parseFloat(lbVt.getText());

                lbVt.setText(v1 + (v2 * qt) + "");
                DefaultTableModel dtmProduto = (DefaultTableModel) JtProdutos.getModel();
                Object[] dados = {lbCod.getText(), comboboxProduto.getSelectedItem(), v2, enQtd.getText(), (v2 * qt), "remover"};
                dtmProduto.addRow(dados);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Valor inserido não numerico");
                enQtd.setText("0");
                enValEn.setText("0");
                envl.setText("0");
                lbVt.setText("0");
                comboboxProduto.setSelectedItem("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Confira se o valor e a quantidade foram inseridos.");
        }
        enQtd.setText("0");
        enValEn.setText("0");
        envl.setText("0");

        comboboxProduto.setSelectedItem("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void JtProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtProdutosMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        String s = source.getModel().getValueAt(row, column) + "";
        int qtd = Integer.parseInt(source.getModel().getValueAt(row, 3) + "");
        float valor_removido = Float.parseFloat(source.getModel().getValueAt(row, 2) + "");
        if (s.equals("remover")) {
            JTextField username = new JTextField();
            JPasswordField password = new JPasswordField();
            Object[] message = {
                "Username:", username,
                "Password:", password
            };

            int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);
            try {
                int user = Integer.parseInt(username.getText());
                if (option == JOptionPane.OK_OPTION) {
                    Usuario_controle uc = new Usuario_controle();
                    if (uc.efetuarLoginAdm(user, password.getText())) {
                        ((DefaultTableModel) JtProdutos.getModel()).removeRow(row);
                        float vtAntes = Float.parseFloat(lbVt.getText());
                        lbVt.setText((vtAntes - valor_removido) + "");
                        this.qtdt=this.qtdt-qtd;
                    } else {
                        JOptionPane.showMessageDialog(null, "Acesso negado");

                    }

                } else {

                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "O codigo do usuário inseridodeve ser numerico. Tente Novamente!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "clique sobre em remover");
        }
    }//GEN-LAST:event_JtProdutosMouseClicked

    private void JtProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtProdutosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtProdutosKeyPressed

    private void comboboxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxProdutoActionPerformed
        // TODO add your handling code here:
        int indiceDoCombo = comboboxProduto.getSelectedIndex();
        String textoDoCombo = comboboxProduto.getSelectedItem().toString();

        if (textoDoCombo != " ") {
            for (int i = 0; i < this.produtos.size(); i++) {
                if (this.produtos.get(i).getNome() == textoDoCombo) {
                    this.envl.setText(this.produtos.get(i).getValor_venda() + "");
                    this.lbCod.setText(this.produtos.get(i).getCod_produto() + "");
                }

            }
        } else {
            lbVt.setText("0");
        }

    }//GEN-LAST:event_comboboxProdutoActionPerformed

    private void comboboxProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboboxProdutoMouseClicked
        // NESSE METODO ESTA SENDO EDITADO O VALOR DE ACORDO COM O QUE É SELECIONADO NO DROPDOWN:


    }//GEN-LAST:event_comboboxProdutoMouseClicked

    private void enQtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enQtdMouseClicked
        // TODO add your handling code here:
        enQtd.setText("");
    }//GEN-LAST:event_enQtdMouseClicked

    private void enValEnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enValEnMouseClicked
        // TODO add your handling code here:
        enValEn.setText("");
    }//GEN-LAST:event_enValEnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControleCaixa;
    private javax.swing.JTable JtProdutos;
    private javax.swing.JComboBox<String> comboboxProduto;
    private javax.swing.JTextField enQtd;
    private javax.swing.JTextField enValEn;
    private javax.swing.JTextField enVl;
    private javax.swing.JLabel envl;
    private javax.swing.JLabel ico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbTroco;
    private javax.swing.JLabel lbTroco1;
    private javax.swing.JLabel lbVt;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
