/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viw;

//IMPORTAÇÕES NECESSARIAS
import controle.ItemVenda_controle;
import controle.NotaVenda_controle;
import controle.Produto_controle;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import controle.Usuario_controle;
import java.awt.Color;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JPasswordField;
import javax.swing.table.TableModel;
import model.ItemVenda_modelo;
import model.NotaVenda_modelo;
import model.Produto_modelo;
//import modelo.Produto;

/**
 * /**
 *
 * @author JOSÉ ULISSES DA SILVA FILHO
 */
public class TelaCaixaVenda extends javax.swing.JInternalFrame {

    ArrayList<Produto_modelo> produtos = new ArrayList<Produto_modelo>();
    //VARIAVEL RANDOM PARA SORTEAR O NUMERODA NOTA
    private Random sorte = new Random();
    //VARIAVEL QUE RECEBE O NUMERO SORTEADO
    private int numeronota = 0;
    private int qtdt = 0;
    private int cod_usuario;

    /**
     * Creates new form TelaCaixa
     */
    public TelaCaixaVenda(int cod_usuario) {
        initComponents();
        //O CODIGO ABAIXO SERVE´PARA PRENCHER O COMBO BOX COM OS ITENS QUE VEM DO BANCO DE CONTROLE CONFORME O PADRÃO MVC  
        this.cod_usuario = cod_usuario;
        try {
            this.produtos = (new Produto_controle().buscarprodutos());
            for (int i = 0; i < this.produtos.size(); i++) {
                this.cmbListaProdutos.addItem(this.produtos.get(i).getNome());
            }
        } catch (Exception e) {
            //MENSAGEM DE ERRO EXIBIDA EM CASO DE EXCEÇÃO  NA INSERÇÃODOS ITENS NA CAIXA DE COMBINAÇÃO
            System.out.println("erro na exibição dos produtos" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        enVl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbTroco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        root = new javax.swing.JPanel();
        ControleCaixa = new javax.swing.JPanel();
        lbCod = new javax.swing.JLabel();
        lblConProdutoTitulo = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JToggleButton();
        btnCancelarCarrinho = new javax.swing.JToggleButton();
        ico = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTrocoTitulo = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        btnAdicionarProdutos = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCalcularTroco = new javax.swing.JToggleButton();
        txtValEn = new javax.swing.JTextField();
        txtProdutoTitulo = new javax.swing.JLabel();
        lblDinheiroEntadaTitulo = new javax.swing.JLabel();
        lblQtdTitulo = new javax.swing.JLabel();
        lbVt = new javax.swing.JLabel();
        lblValorTotalTitulo = new javax.swing.JLabel();
        lblValorProdutoTitulo = new javax.swing.JLabel();
        cmbListaProdutos = new javax.swing.JComboBox<>();
        txtValorProduto = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        btnAjuda = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaCarrinhoCompra = new javax.swing.JTable();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Valor");

        enVl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enVl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enVlActionPerformed(evt);
            }
        });
        enVl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enVlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enVlKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Troco");

        lbTroco.setBackground(new java.awt.Color(255, 255, 255));
        lbTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTroco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adicionar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton4.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setText("Finaliza");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(51, 153, 255));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("Cancelar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        setMinimumSize(new java.awt.Dimension(650, 531));
        setPreferredSize(new java.awt.Dimension(650, 531));

        root.setBackground(new java.awt.Color(255, 0, 0));
        root.setLayout(new java.awt.CardLayout());

        ControleCaixa.setBackground(new java.awt.Color(255, 255, 255));
        ControleCaixa.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        lbCod.setBackground(new java.awt.Color(255, 255, 255));
        lbCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCod.setText(" ");

        lblConProdutoTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConProdutoTitulo.setForeground(new java.awt.Color(0, 8, 90));
        lblConProdutoTitulo.setText("Codigo do produto:");

        btnFinalizarCompra.setBackground(new java.awt.Color(0, 8, 90));
        btnFinalizarCompra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFinalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarCompra.setText("Finalizar compra");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        btnCancelarCarrinho.setBackground(new java.awt.Color(150, 0, 0));
        btnCancelarCarrinho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelarCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCarrinho.setText("Cancelar compras");
        btnCancelarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCarrinhoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTrocoTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTrocoTitulo.setForeground(new java.awt.Color(0, 8, 90));
        lblTrocoTitulo.setText("Troco");

        lblTroco.setBackground(new java.awt.Color(255, 255, 255));
        lblTroco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTroco.setText("0");
        lblTroco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 8, 90)));

        btnAdicionarProdutos.setBackground(new java.awt.Color(0, 8, 90));
        btnAdicionarProdutos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdicionarProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarProdutos.setText("Adicionar Item");
        btnAdicionarProdutos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionarProdutos.setBorderPainted(false);
        btnAdicionarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutosActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 8, 90));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCalcularTroco.setBackground(new java.awt.Color(0, 8, 90));
        btnCalcularTroco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalcularTroco.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularTroco.setText("Calcular troco");
        btnCalcularTroco.setMinimumSize(new java.awt.Dimension(175, 31));
        btnCalcularTroco.setPreferredSize(new java.awt.Dimension(175, 30));
        btnCalcularTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTrocoActionPerformed(evt);
            }
        });

        txtValEn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValEn.setText("0");
        txtValEn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 8, 90)));
        txtValEn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValEnMouseClicked(evt);
            }
        });
        txtValEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValEnActionPerformed(evt);
            }
        });

        txtProdutoTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProdutoTitulo.setForeground(new java.awt.Color(0, 8, 90));
        txtProdutoTitulo.setText("Produto");

        lblDinheiroEntadaTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDinheiroEntadaTitulo.setForeground(new java.awt.Color(0, 8, 90));
        lblDinheiroEntadaTitulo.setText("Dinheiro Entrada");

        lblQtdTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQtdTitulo.setForeground(new java.awt.Color(0, 8, 90));
        lblQtdTitulo.setText("Quantidade");

        lbVt.setBackground(new java.awt.Color(255, 255, 255));
        lbVt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbVt.setText("0");
        lbVt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 8, 90)));

        lblValorTotalTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorTotalTitulo.setForeground(new java.awt.Color(0, 8, 90));
        lblValorTotalTitulo.setText("Valor Total");

        lblValorProdutoTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorProdutoTitulo.setForeground(new java.awt.Color(0, 8, 90));
        lblValorProdutoTitulo.setText("Valor");

        cmbListaProdutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE UM PRODUTO" }));
        cmbListaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbListaProdutosMouseClicked(evt);
            }
        });
        cmbListaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaProdutosActionPerformed(evt);
            }
        });

        txtValorProduto.setBackground(new java.awt.Color(255, 255, 255));
        txtValorProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValorProduto.setText("0");
        txtValorProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 8, 90)));

        txtQtd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQtd.setText("0");
        txtQtd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 8, 90)));
        txtQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtdMouseClicked(evt);
            }
        });

        btnAjuda.setBackground(new java.awt.Color(0, 8, 90));
        btnAjuda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAjuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAjuda.setText("?");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTroco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQtdTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbVt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorProdutoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQtd)
                    .addComponent(lblTrocoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbListaProdutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValorTotalTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDinheiroEntadaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdutoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtValEn)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtProdutoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbListaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQtdTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValorProdutoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblValorTotalTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDinheiroEntadaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrocoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tabelaCarrinhoCompra.setForeground(new java.awt.Color(0, 8, 90));
        tabelaCarrinhoCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "Produto", "Valor", "Quantidade", "vatol total unitario", "Remover"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCarrinhoCompra.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaCarrinhoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCarrinhoCompraMouseClicked(evt);
            }
        });
        tabelaCarrinhoCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaCarrinhoCompraKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaCarrinhoCompra);

        javax.swing.GroupLayout ControleCaixaLayout = new javax.swing.GroupLayout(ControleCaixa);
        ControleCaixa.setLayout(ControleCaixaLayout);
        ControleCaixaLayout.setHorizontalGroup(
            ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControleCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControleCaixaLayout.createSequentialGroup()
                        .addComponent(lblConProdutoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControleCaixaLayout.createSequentialGroup()
                        .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ControleCaixaLayout.createSequentialGroup()
                                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(ico)
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        ControleCaixaLayout.setVerticalGroup(
            ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControleCaixaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConProdutoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ControleCaixaLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(ico)
                        .addGap(88, 88, 88))
                    .addGroup(ControleCaixaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addGroup(ControleCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
            .addGroup(ControleCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        root.add(ControleCaixa, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enVlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enVlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enVlActionPerformed

    private void enVlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enVlKeyPressed

    }//GEN-LAST:event_enVlKeyPressed

    private void enVlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enVlKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_enVlKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed

    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

    }//GEN-LAST:event_jToggleButton3ActionPerformed
    /*O CODIGO ABAIXO FAZ E RESPONSAVEL PELA AUTENTICAÇÃO E CANCELAMENTO DOS ITENS INSERIDOS NA TABELA E POR LIMPAR A TABELA */
    private void btnCancelarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCarrinhoActionPerformed
        // O CODIGO ABAIXO CRIA UM JOPTIONPANE QUE TERA UM CAMPO USUARIO E SENHA E ATRAVES DELE SERA FEITA A AUTENTICAÇÃO DOS 
        //DADOS PARA PERMITIR O CANCELAMENTO DOS PRODUTOS
        JTextField username = new JTextField();
        JPasswordField password = new JPasswordField();
        Object[] message = {
            "Username:", username,
            "Password:", password
        };
        //O CODIGO ABAIXO FAZ O TESTE NA TABELA PARA SABER SE TEM ALGUM ITEM NA TABELA PARA SER CANCELADO
        //SE TIVER ELE SERA CANCELADO CASO NÃO HAJA SERA RETORNADA UMA MENSAGEM DE ERRO
        if (tabelaCarrinhoCompra.getModel().getRowCount() != 0) {
            int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                Usuario_controle uc = new Usuario_controle();
                try {
                    lbVt.setText("0");
                    int user = Integer.parseInt(username.getText());
                    if (uc.efetuarLoginAdm(user, password.getText())) {
                        int rowf = tabelaCarrinhoCompra.getRowCount();
                        int i = 1;
                        if (tabelaCarrinhoCompra.getModel().getRowCount() > 0) {
                            while (tabelaCarrinhoCompra.getModel().getRowCount() > 0) {
                                ((DefaultTableModel) tabelaCarrinhoCompra.getModel()).removeRow(0);
                                ((DefaultTableModel) tabelaCarrinhoCompra.getModel()).removeRow(0);
                            }
                        } else {
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Acesso negado");

                    }
                } catch (Exception e) {
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "nenhum item adicionado");
        }

    }//GEN-LAST:event_btnCancelarCarrinhoActionPerformed
//O CODIGO A BAIXO É ASIONADO COM UM CLICK EM FINALIZAR COMPRA E ELE E RESPONSAVEL POR
//CRIA A NOTA DA COMPRA E SALVAR A COMPRA NO BANCO DE DADOSNAS TABELAS ITEMVENDA E NOTAVENDA
    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        try {
            //O IF ABAIXO TESTA SE A TABELA ESTA VAZIA CASO ESTEJA ELE RETOORNA UMA MENSAGEM DE ERRO CASO NÃO ERETORNADA UMA MENSAGEM DE ERRO
            if (tabelaCarrinhoCompra.getModel().getRowCount() != 0) {
                float vt = Float.parseFloat(lbVt.getText());
                //O CODIGO BAIXO CAPTURA DATA E HORA ATUAL DA MAQUINA 
                LocalDateTime data = LocalDateTime.now();
                String datahora = data + "";
                String dataformatada = datahora.substring(0, 10);
                String horaformatada = datahora.substring(11, 19);

                int qtd = Integer.parseInt(txtQtd.getText());

                //OCODIGO ABAIXOE RESPONSAVEL POR CRIAR O NOTA E PASSAR UM MODELDE NOTA PARA INSERÇÃODE DADOS ATRAVÉS DO CONTROLER SEGUINDO OS PADRÕES MVC 
                try {
                    float vt_insert = Float.parseFloat(lbVt.getText());
                    NotaVenda_modelo nota_modelo = new NotaVenda_modelo(this.cod_usuario, 0, 0, vt, datahora, datahora, horaformatada, this.qtdt, vt_insert);
                    this.numeronota = new NotaVenda_controle().inserirNotas(nota_modelo);
                } catch (Exception e) {
                    System.err.println("erro ao inserir a nota no bd na tela caixa no butão finalizar:" + e);
                }

                NotaVenda_modelo notaob = new NotaVenda_modelo(cod_usuario, 0, numeronota, vt, dataformatada, dataformatada, horaformatada, this.qtdt, vt);
                if (numeronota != 0) {
                    this.setVisible(false);
                    TelaNota_Venda nota = new TelaNota_Venda(tabelaCarrinhoCompra, notaob, 1);
                    nota.setVisible(true);

                } else {
                    TelaNota_Venda nota = new TelaNota_Venda(tabelaCarrinhoCompra, notaob, 2);
                    nota.setVisible(true);

                }

//              O CODIGO ABAIXO ÉRESPONSAVEL POR CRIAR UM ITEM VENDA E PASSAR UM MODEL ITEM VENDA PARA A PERSISTENCIA DOS DADOS NO BANCO ATRAVES DO MODELO_ITEMVENDA
                TableModel mdtb = tabelaCarrinhoCompra.getModel();

                ArrayList<ItemVenda_modelo> itens = new ArrayList<ItemVenda_modelo>();
                try {
                    for (int i = 0; i < mdtb.getRowCount(); i++) {
                        ItemVenda_modelo item = new ItemVenda_modelo();
                        item.setProduto_cod_produto(Integer.parseInt(mdtb.getValueAt(i, 0) + ""));
                        item.setDatacad(dataformatada);
                        item.setHoracad(horaformatada);
                        item.setNotavenda_cod_venda(numeronota);
                        item.setValor(Float.parseFloat(mdtb.getValueAt(i, 2) + ""));
                        item.setQuantidade(Integer.parseInt(mdtb.getValueAt(i, 3) + ""));
                        item.setValor_total(Float.parseFloat(mdtb.getValueAt(i, 4) + ""));
                        itens.add(item);

                    }
                    boolean result = new ItemVenda_controle().salvaritens(itens, this.numeronota);
                    if (result == false) {
                        System.out.println("item venda inserido com sucesso");
                    } else {
                        System.out.println("inserção de item falhou");
                    }
                } catch (ArrayIndexOutOfBoundsException e) {
                    System.out.println("erro ao inserir item venda" + e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "não foi inserido nenhum item");
            }

        } catch (Exception e) {
            System.out.println("Erro ao abrir tela caixa" + e);
        }

    }//GEN-LAST:event_btnFinalizarCompraActionPerformed
//O CODIGO ABAIXOCAPTURA O VALOR INSERIDO EM VALOR DE ENTRADA E E VALOR TOTAL E CONVERTE AMBOS EM FLOAT FAZ O CALCULO 
//DE TROCO
    private void btnCalcularTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTrocoActionPerformed
        try {
            String entrada = txtValEn.getText();
            String entradarefatorada = entrada.replaceAll(",", ".");
            float v1 = Float.parseFloat(lbVt.getText());
            float v2 = Float.parseFloat(entradarefatorada);
            if (v2 <= 0) {

            } else {
                float troco = v2 - v1;
                DecimalFormat formatadortroco = new DecimalFormat("0.00");
                lblTroco.setText((formatadortroco.format(troco)) + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "cheque o valor de entrada ");
        }

    }//GEN-LAST:event_btnCalcularTrocoActionPerformed

    private void txtValEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValEnActionPerformed

    }//GEN-LAST:event_txtValEnActionPerformed
//O CODIGO ABAIXO E RESPNASAVEL POR LIMPRA OS CAPOS DA TELA
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtQtd.setText("0");
        txtValEn.setText("0");
        txtValorProduto.setText("0");
        lblTroco.setText("0");
        cmbListaProdutos.setSelectedItem("");
        cmbListaProdutos.setSelectedIndex(0);

    }//GEN-LAST:event_btnLimparActionPerformed
//O CODIGO ABAIXO E RESPONSAVEL POR ADICIONAR PRODUTOS A TABELA CARRINHO PEGANDO O NOME DO PRODUTO SEU CODIGO O VALOR E O VALOR DA MULTIPLICAÇÃO
    // DA QUANTIDADE POR SEU VALOR UNITARIO
    private void btnAdicionarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutosActionPerformed
        float v2 = Float.parseFloat(txtValorProduto.getText());
        int qt = 0;
        try {
            qt = Integer.parseInt(txtQtd.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "A quantidade inserida deve ser um valor inteiro.");
        }

        this.qtdt += qt;
        if (((v2 != 0) && (qt != 0))) {
            try {
                float v1 = Float.parseFloat(lbVt.getText());

                lbVt.setText(v1 + (v2 * qt) + "");
                DefaultTableModel dtmProduto = (DefaultTableModel) tabelaCarrinhoCompra.getModel();
                Object[] dados = {lbCod.getText(), cmbListaProdutos.getSelectedItem(), v2, txtQtd.getText(), (v2 * qt), "remover"};
                dtmProduto.addRow(dados);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Valor inserido não numerico");
                txtQtd.setText("0");
                txtValEn.setText("0");
                txtValorProduto.setText("0");
                lbVt.setText("0");
                cmbListaProdutos.setSelectedItem("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Confira se o valor e a quantidade foram inseridos.");
        }
        txtQtd.setText("0");
        txtValEn.setText("0");
        txtValorProduto.setText("0");

        cmbListaProdutos.setSelectedItem("");

    }//GEN-LAST:event_btnAdicionarProdutosActionPerformed
//O CODGO ABAIXO E RESPONSAVEL POR REALIZAR UM TESTE SEMPRE QUE FOR EFETUADO UM CLICK SOBRE A TABELA PARA SABER SE ESTA SENDO CLIKADO NO CAMPO
 //   REMOVER CASO SEJA E FEITA A AUTENTICAÇÃO DOS DADOS DE ADM E O PRODUTO E REMOVIDO CASO OCORRA UMA EXCEÇÃO E RETORNADA UMA MENSAGEM DE ERRO DEE ACORDO COM A EXCEÇÃO
    private void tabelaCarrinhoCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCarrinhoCompraMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        String s = source.getModel().getValueAt(row, column) + "";
        int qtd = Integer.parseInt(source.getModel().getValueAt(row, 3) + "");
        float valor_removido = Float.parseFloat(source.getModel().getValueAt(row, 2) + "");
        if (s.equals("remover")) {
            //CRIAÇÃO O PAINEL E OPÇÕES PARA ATENTICAÇÃO DO USUARIO E SENHA DO ADM
            JTextField username = new JTextField();
            JPasswordField password = new JPasswordField();
            Object[] message = {
                "Username:", username,
                "Password:", password
            };

            int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);
            try {
                int user = Integer.parseInt(username.getText());
                if (option == JOptionPane.OK_OPTION) {
                    Usuario_controle uc = new Usuario_controle();
                    if (uc.efetuarLoginAdm(user, password.getText())) {
                        ((DefaultTableModel) tabelaCarrinhoCompra.getModel()).removeRow(row);
                        float vtAntes = Float.parseFloat(lbVt.getText());
                        lbVt.setText((vtAntes - valor_removido) + "");
                        this.qtdt = this.qtdt - qtd;
                    } else {
                        JOptionPane.showMessageDialog(null, "Acesso negado");

                    }

                } else {

                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "O codigo do usuário inseridodeve ser numerico. Tente Novamente!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "clique sobre em remover");
        }
    }//GEN-LAST:event_tabelaCarrinhoCompraMouseClicked

    private void tabelaCarrinhoCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaCarrinhoCompraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaCarrinhoCompraKeyPressed
//O CODIGO ABAIXO E RESPONSAVEL POR ATUALIZAR O VLOR DO PRODUTO DE ACORDO COM O PRODUTO SELECIONADO NA CAIXA DE COMBINAÇÃO
    private void cmbListaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaProdutosActionPerformed
        // TODO add your handling code here:
        int indiceDoCombo = cmbListaProdutos.getSelectedIndex();
        String textoDoCombo = cmbListaProdutos.getSelectedItem().toString();

        if (textoDoCombo != " ") {
            for (int i = 0; i < this.produtos.size(); i++) {
                if (this.produtos.get(i).getNome() == textoDoCombo) {
                    this.txtValorProduto.setText(this.produtos.get(i).getValor_venda() + "");
                    this.lbCod.setText(this.produtos.get(i).getCod_produto() + "");
                }

            }
        } else {
            lbVt.setText("0");
        }

    }//GEN-LAST:event_cmbListaProdutosActionPerformed

    private void cmbListaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbListaProdutosMouseClicked
        // NESSE METODO ESTA SENDO EDITADO O VALOR DE ACORDO COM O QUE É SELECIONADO NO DROPDOWN:


    }//GEN-LAST:event_cmbListaProdutosMouseClicked
//CODIGO A BAIXO LIMPA O CAMPO QUAN SE CLICA SOBRE ELE
    private void txtQtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtdMouseClicked

        txtQtd.setText("");
    }//GEN-LAST:event_txtQtdMouseClicked
//CODIGO A BAIXO LIMPA O CAMPO QUAN SE CLICA SOBRE ELE
    private void txtValEnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValEnMouseClicked
        txtValEn.setText("");
    }//GEN-LAST:event_txtValEnMouseClicked
// OCODIGO ABAIXO SERVE PARA FORNECER AJUDA AO USUARIO NA TELA CAIXA VENDA ALEM DE MODIFICAR A COR DO BOTÃO AO PRECIONALO
    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ao abrir o dropdown de produtos você pode digitar o nome do produto que ele ira aparecer!");
        btnAjuda.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnAjudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControleCaixa;
    private javax.swing.JButton btnAdicionarProdutos;
    private javax.swing.JToggleButton btnAjuda;
    private javax.swing.JToggleButton btnCalcularTroco;
    private javax.swing.JToggleButton btnCancelarCarrinho;
    private javax.swing.JToggleButton btnFinalizarCompra;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbListaProdutos;
    private javax.swing.JTextField enVl;
    private javax.swing.JLabel ico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbTroco;
    private javax.swing.JLabel lbVt;
    private javax.swing.JLabel lblConProdutoTitulo;
    private javax.swing.JLabel lblDinheiroEntadaTitulo;
    private javax.swing.JLabel lblQtdTitulo;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblTrocoTitulo;
    private javax.swing.JLabel lblValorProdutoTitulo;
    private javax.swing.JLabel lblValorTotalTitulo;
    private javax.swing.JPanel root;
    private javax.swing.JTable tabelaCarrinhoCompra;
    private javax.swing.JLabel txtProdutoTitulo;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtValEn;
    private javax.swing.JLabel txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
