
package viw;

import controle.NotaVenda_controle;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.NotaVenda_modelo;

/**
 *
 * @author sulis
 */
public class TelaNota_Venda extends javax.swing.JFrame {
    private NotaVenda_modelo nota_local ;
    private JTable tabela;
    private int sinal;
    /**
     * O CODIGO ABAIXO CRIA UM NOVO FORMULARIO TELA NOTA VENDA
     */
    
    public TelaNota_Venda(JTable tabela,NotaVenda_modelo nota,int sinal) {
        initComponents();
        //O CODIGO ABAIXO INSERE AS INFORMAÇÕES NA TELA NOTA E MOSTRA O STATUS DA NOTA SE FOI OU NÃO SALVA NO BANCO
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); 
        this.sinal = sinal;
        this.nota_local = nota;
        this.tabela=tabela;
        try {
            jTprodutosnota.setModel(tabela.getModel());
            lbDatanota.setText("Data: "+nota.getData());
            lbNumeronota.setText("Numer da nota: "+nota.getCod_venda());
            lbvalortotal.setText("Total: "+nota.getValor_total());
            lbtotalitem.setText("N° de itens:"+nota.getQuantidade());
            NotaVenda_controle nota_controle = new NotaVenda_controle();
            if(sinal==1){
                lbstatus.setText("nota salva");
                lbstatus.setForeground(Color.GREEN);
            } else {
                lbstatus.setText("não salva");
                lbstatus.setForeground(Color.GREEN);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar nota");
        }
        
    }

    private TelaNota_Venda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelImprecao = new javax.swing.JPanel();
        btOk = new javax.swing.JToggleButton();
        lbltitulo = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();
        lbtotalitem = new javax.swing.JLabel();
        lbDatanota = new javax.swing.JLabel();
        lbItemNota = new javax.swing.JLabel();
        lbNumeronota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTprodutosnota = new javax.swing.JTable();
        lbvalortotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelImprecao.setBackground(new java.awt.Color(255, 255, 255));

        btOk.setBackground(new java.awt.Color(0, 8, 90));
        btOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btOk.setForeground(new java.awt.Color(255, 255, 255));
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(0, 8, 90));
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Nota");

        lbstatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbstatus.setForeground(new java.awt.Color(0, 8, 90));
        lbstatus.setText("Status");

        lbtotalitem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtotalitem.setForeground(new java.awt.Color(0, 8, 90));
        lbtotalitem.setText("N° de itens:");

        lbDatanota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDatanota.setForeground(new java.awt.Color(0, 8, 90));
        lbDatanota.setText("Data:");

        lbItemNota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbItemNota.setForeground(new java.awt.Color(0, 8, 90));
        lbItemNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbItemNota.setText("Itens");

        lbNumeronota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNumeronota.setForeground(new java.awt.Color(0, 8, 90));
        lbNumeronota.setText("Numer:");

        jTprodutosnota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTprodutosnota);

        lbvalortotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbvalortotal.setForeground(new java.awt.Color(0, 8, 90));
        lbvalortotal.setText("Valor Total:");

        javax.swing.GroupLayout painelImprecaoLayout = new javax.swing.GroupLayout(painelImprecao);
        painelImprecao.setLayout(painelImprecaoLayout);
        painelImprecaoLayout.setHorizontalGroup(
            painelImprecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
            .addGroup(painelImprecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelImprecaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelImprecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelImprecaoLayout.createSequentialGroup()
                            .addComponent(lbDatanota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(104, 104, 104))
                        .addComponent(lbItemNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumeronota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelImprecaoLayout.createSequentialGroup()
                            .addComponent(lbvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbtotalitem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btOk, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        painelImprecaoLayout.setVerticalGroup(
            painelImprecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(painelImprecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelImprecaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbltitulo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbNumeronota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbDatanota)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbItemNota)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(painelImprecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbvalortotal, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(lbstatus)
                        .addComponent(btOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbtotalitem))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelImprecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelImprecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
                                             
        try {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("printar nota");
            job.setPrintable(new Printable(){
                public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) {
                    if(pageIndex>0){
                        return  Printable.NO_SUCH_PAGE;
                    }
                    Graphics2D g2 = (Graphics2D)graphics;
                    g2.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                    g2.scale(0.900,1.00);
                    
                    painelImprecao.print(g2);
               
                    return Printable.PAGE_EXISTS;
                    
                }
                
            });
            job.printDialog();
            job.print();
            this.setVisible(false);
        } catch (PrinterException ex) { }  
        
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            NotaVenda_modelo nota_local = this.nota_local;
            JTable tabela = this.tabela;
            int sinal = this.sinal;

            public void run() { 
                new TelaNota_Venda(tabela,this.nota_local,sinal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTprodutosnota;
    private javax.swing.JLabel lbDatanota;
    private javax.swing.JLabel lbItemNota;
    private javax.swing.JLabel lbNumeronota;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbstatus;
    private javax.swing.JLabel lbtotalitem;
    private javax.swing.JLabel lbvalortotal;
    private javax.swing.JPanel painelImprecao;
    // End of variables declaration//GEN-END:variables
}
