
package viw;

import controle.NotaVenda_controle;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.NotaVenda_modelo;

/**
 *
 * @author sulis
 */
public class TelaNota_Venda extends javax.swing.JFrame {
    private NotaVenda_modelo nota_local ;
    private JTable tabela;
    private int sinal;
    /**
     * Creates new form notavendaex
     */
    
    public TelaNota_Venda(JTable tabela,NotaVenda_modelo nota,int sinal) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); 
        this.sinal = sinal;
        this.nota_local = nota;
        this.tabela=tabela;
        try {
            jTprodutosnota.setModel(tabela.getModel());
            lbDatanota.setText("Data: "+nota.getData());
            lbNumeronota.setText("Numer da nota: "+nota.getCod_venda());
            lbvalortotal.setText("Total: "+nota.getValor_total());
            lbtotalitem.setText("N° de itens:"+nota.getQuantidade());
            NotaVenda_controle nota_controle = new NotaVenda_controle();
            if(sinal==1){
                lbstatus.setText("nota salva");
                lbstatus.setForeground(Color.GREEN);
            } else {
                lbstatus.setText("não salva");
                lbstatus.setForeground(Color.GREEN);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar nota");
        }
        
    }

    private TelaNota_Venda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbvalortotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTprodutosnota = new javax.swing.JTable();
        lbDatanota = new javax.swing.JLabel();
        lbItemNota = new javax.swing.JLabel();
        lbNumeronota = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();
        btOk = new javax.swing.JToggleButton();
        lbtotalitem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbvalortotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbvalortotal.setText("Valor Total:");

        jTprodutosnota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTprodutosnota);

        lbDatanota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDatanota.setText("Data:");

        lbItemNota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbItemNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbItemNota.setText("Itens");

        lbNumeronota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNumeronota.setText("Numer:");

        lbltitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Nota");

        lbstatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbstatus.setText("Status");

        btOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        lbtotalitem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbtotalitem.setText("N° de itens:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDatanota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbItemNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNumeronota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbvalortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbtotalitem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btOk, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumeronota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDatanota)
                .addGap(4, 4, 4)
                .addComponent(lbItemNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbvalortotal, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lbstatus)
                    .addComponent(btOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbtotalitem)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNota_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            NotaVenda_modelo nota_local = this.nota_local;
            JTable tabela = this.tabela;
            int sinal = this.sinal;

            public void run() { 
                new TelaNota_Venda(tabela,this.nota_local,sinal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTprodutosnota;
    private javax.swing.JLabel lbDatanota;
    private javax.swing.JLabel lbItemNota;
    private javax.swing.JLabel lbNumeronota;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbstatus;
    private javax.swing.JLabel lbtotalitem;
    private javax.swing.JLabel lbvalortotal;
    // End of variables declaration//GEN-END:variables
}
