/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viw;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSÉ ULISSES DA SILVA FILHO / EMESSON CAVALCANTE
 */
public class TelaPrincipal extends javax.swing.JFrame {
//    INICIALIZAÇÃO DAS TELAS

    private TelaHome th;
    private TelaRh trh;
    private int cod_usuario;
    private TelaCaixaVenda tcv;
    private TelaBuscar_Notas bcn;
    private TelaCriarLogin tcl;
    private TelaRelatorio trv;
    private TelaEstoque tes;
    private TelaSobre ts;
    private TelaAjuda ta;

    /**
     * CRIAÇÃO DE UMNOVO FORMULARIOS TelaPrincipal
     */
    public TelaPrincipal(int cod_usuario) {
        initComponents();
        
        // Define o tamanhos mínimo da JFrame
        this.setMinimumSize(new Dimension(1000, 600));

//      COLOCANDO A TELA PRINCIPAL E A TELA HOME EM TAMANHO MAXIMO
        try {
            this.setExtendedState(MAXIMIZED_BOTH);
            this.th = new TelaHome();
            this.th.setVisible(true);
            this.desktop.add(this.th);
            this.th.setMaximum(true);
        } catch (Exception e) {
        }
        this.cod_usuario = cod_usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menHome = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menCaixa = new javax.swing.JMenu();
        abrMenCaixa = new javax.swing.JMenuItem();
        abrBusca = new javax.swing.JMenuItem();
        menRh = new javax.swing.JMenu();
        abrRecHum = new javax.swing.JMenuItem();
        abrCriarLogin = new javax.swing.JMenuItem();
        menEstoque = new javax.swing.JMenu();
        abrMenEstoque = new javax.swing.JMenuItem();
        menRelatorio = new javax.swing.JMenu();
        menRelatorioVenda = new javax.swing.JMenuItem();
        menSobre = new javax.swing.JMenu();
        abrMenSobre = new javax.swing.JMenuItem();
        menOpcoes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        abrTrocarUsuario = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MercoCenter System");
        setMinimumSize(new java.awt.Dimension(650, 531));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        menHome.setText("Home");
        menHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menHomeActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/botao-home.png"))); // NOI18N
        jMenuItem1.setText("Abrir tela Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menHome.add(jMenuItem1);

        jMenuBar1.add(menHome);

        menCaixa.setText("Caixa");
        menCaixa.setEnabled(false);

        abrMenCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        abrMenCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/apenas-a-dinheiro.png"))); // NOI18N
        abrMenCaixa.setText("Abrir Caixa");
        abrMenCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrMenCaixaActionPerformed(evt);
            }
        });
        menCaixa.add(abrMenCaixa);

        abrBusca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        abrBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/busca-de-conhecimento.png"))); // NOI18N
        abrBusca.setText("Abrir Busca");
        abrBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrBuscaActionPerformed(evt);
            }
        });
        menCaixa.add(abrBusca);

        jMenuBar1.add(menCaixa);

        menRh.setText("RH");
        menRh.setEnabled(false);
        menRh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRhActionPerformed(evt);
            }
        });

        abrRecHum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        abrRecHum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/recursos-humanos.png"))); // NOI18N
        abrRecHum.setText("Abrir Recursos Humanos");
        abrRecHum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrRecHumActionPerformed(evt);
            }
        });
        menRh.add(abrRecHum);

        abrCriarLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        abrCriarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/user.png"))); // NOI18N
        abrCriarLogin.setText("Criar login");
        abrCriarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrCriarLoginActionPerformed(evt);
            }
        });
        menRh.add(abrCriarLogin);

        jMenuBar1.add(menRh);

        menEstoque.setText("Estoque");
        menEstoque.setEnabled(false);

        abrMenEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        abrMenEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/estoque.png"))); // NOI18N
        abrMenEstoque.setText("Abrir Estoque");
        abrMenEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrMenEstoqueActionPerformed(evt);
            }
        });
        menEstoque.add(abrMenEstoque);

        jMenuBar1.add(menEstoque);

        menRelatorio.setText("Relatorio");
        menRelatorio.setEnabled(false);

        menRelatorioVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menRelatorioVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/relatorio-32px.png"))); // NOI18N
        menRelatorioVenda.setText("Abrir relatorio de venda");
        menRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelatorioVendaActionPerformed(evt);
            }
        });
        menRelatorio.add(menRelatorioVenda);

        jMenuBar1.add(menRelatorio);

        menSobre.setText("Sobre");

        abrMenSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        abrMenSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/sobre.png"))); // NOI18N
        abrMenSobre.setText("Abrir sobre");
        abrMenSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrMenSobreActionPerformed(evt);
            }
        });
        menSobre.add(abrMenSobre);

        jMenuBar1.add(menSobre);

        menOpcoes.setText("Opções");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/central-de-ajuda.png"))); // NOI18N
        jMenuItem2.setText("Abrir ajuda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menOpcoes.add(jMenuItem2);

        abrTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        abrTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/sair.png"))); // NOI18N
        abrTrocarUsuario.setText("Trocar de usuário");
        abrTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrTrocarUsuarioActionPerformed(evt);
            }
        });
        menOpcoes.add(abrTrocarUsuario);

        menSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viw/img/telaPrincipal/cancel.png"))); // NOI18N
        menSair.setText("Fechar sistema");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpcoes.add(menSair);

        jMenuBar1.add(menOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As ações a seguir serão executadas quando a TelaPrincipal for iniciada
    }//GEN-LAST:event_formWindowActivated

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        // exibe uma caixa de diálogo pra confirmar se quer sair sim ou nao
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menSairActionPerformed

    private void menRhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRhActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menRhActionPerformed
//METODO PARA ABERTURA DA TELA DE RECURSOS HUMANOS
    private void abrRecHumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrRecHumActionPerformed

        if (trh == null) {
            fecharOutrasTelas();

            trh = new TelaRh();
            trh.setVisible(true);

            desktop.add(trh);

            try {

                trh.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("A tela já está aparecendo!");
        }


    }//GEN-LAST:event_abrRecHumActionPerformed
//NESSE METODO ESTASENDO VERIFICADO SE EXISTE ALGUMA TELA ABERTA E FECHANDOO ELA PARA ABERTURA 
    private void abrMenCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrMenCaixaActionPerformed

        if (tcv == null) {
            fecharOutrasTelas();

            tcv = new TelaCaixaVenda(cod_usuario);
            tcv.setVisible(true);
            desktop.add(tcv);
            try {
                tcv.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (tcv.isVisible() == false) {
                tcv = new TelaCaixaVenda(cod_usuario);
                tcv.setVisible(true);
                desktop.add(tcv);
            } else {
                System.out.println("A tela já está aparecendo!");
            }
        }


    }//GEN-LAST:event_abrMenCaixaActionPerformed

    private void abrBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrBuscaActionPerformed
        if (bcn == null) {
            fecharOutrasTelas();

            bcn = new TelaBuscar_Notas();
            bcn.setVisible(true);

            desktop.add(bcn);
            try {
                bcn.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("A tela já está aparecendo!");
        }

    }//GEN-LAST:event_abrBuscaActionPerformed

    private void menHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menHomeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_menHomeActionPerformed
    private void navegacao(JInternalFrame telaSolicitada) {
        try {
            if (this.th != null) {
                this.th.setVisible(false);
                desktop.remove(this.th);
                tcv = new TelaCaixaVenda(this.cod_usuario);
                this.tcv.setVisible(true);
                desktop.add(this.tcv);
                this.tcv.setMaximum(true);
                this.th = null;
            }
            if (this.trh != null) {
                this.trh.setVisible(false);
                desktop.remove(this.trh);
                tcv = new TelaCaixaVenda(this.cod_usuario);
                this.tcv.setVisible(true);
                desktop.add(this.tcv);
                this.tcv.setMaximum(true);
                this.trh = null;
            }
            if (this.bcn != null) {
                this.bcn.setVisible(false);
                desktop.remove(this.bcn);
                tcv = new TelaCaixaVenda(this.cod_usuario);
                this.tcv.setVisible(true);
                desktop.add(this.tcv);
                this.tcv.setMaximum(true);
                this.bcn = null;
            }
            if (this.tcv != null) {
                if (this.tcv.isVisible() == false) {
                    desktop.remove(this.tcv);
                    this.tcv = new TelaCaixaVenda(cod_usuario);
                    this.tcv.setVisible(true);
                    this.desktop.add(this.tcv);
                    this.tcv.setMaximum(true);
                } else {
                }
            }
        } catch (Exception e) {
            System.out.println("Erro ao abrir tela caixa" + e);
        }

    }

//ESSE METODO ABRE A CLASSE HOME FAZENDO TESTES PARA SABER SE HA MAIS ALGUMA TELA ABERTA
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (this.th == null) {
            fecharOutrasTelas();

            th = new TelaHome();
            th.setVisible(true);

            desktop.add(th);
            try {
                th.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("A tela já está aparecendo!");
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void abrCriarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrCriarLoginActionPerformed
        // TODO add your handling code here:
        if (tcl == null) {
            fecharOutrasTelas();

            tcl = new TelaCriarLogin();
            tcl.setVisible(true);

            desktop.add(this.tcl);

            try {
                this.tcl.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("A tela já está aparecendo.");

        }
    }//GEN-LAST:event_abrCriarLoginActionPerformed

    private void abrMenEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrMenEstoqueActionPerformed
        // TODO add your handling code here:
        if (this.tes == null) {
            fecharOutrasTelas();

            try {
                this.tes = new TelaEstoque();
            } catch (ParseException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            tes.setVisible(true);

            desktop.add(tes);
            try {
                tes.setMaximum(true);
            } catch (PropertyVetoException ex) {
                System.out.println(ex);
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("O tela já está aparecendo!");
        }
    }//GEN-LAST:event_abrMenEstoqueActionPerformed

    private void menRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelatorioVendaActionPerformed
        // TODO add your handling code here:
        if (this.trv == null) {
            fecharOutrasTelas();

            this.trv = new TelaRelatorio();
            trv.setVisible(true);

            desktop.add(trv);
            try {
                trv.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("O tela já está aparecendo!");
        }
    }//GEN-LAST:event_menRelatorioVendaActionPerformed

    private void abrTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrTrocarUsuarioActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja fazer logout?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
            TelaLogin login = new TelaLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_abrTrocarUsuarioActionPerformed

    private void abrMenSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrMenSobreActionPerformed
        if (this.ts == null) {
            fecharOutrasTelas();

            this.ts = new TelaSobre();
            ts.setVisible(true);

            desktop.add(ts);

            try {
                ts.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("O tela já está aparecendo!");
        }
    }//GEN-LAST:event_abrMenSobreActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (this.ta == null) {
            fecharOutrasTelas();

            this.ta = new TelaAjuda();
            ta.setVisible(true);

            desktop.add(ta);

            try {
                ta.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("O tela já está aparecendo!");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void fecharOutrasTelas() {
        // Fecha tela relatorio
        if (this.trv != null) {
            this.trv.setVisible(false);
            desktop.remove(this.trv);
            this.trv = null;
        }
        // Fecha Página Inicial
        if (this.th != null) {
            this.th.setVisible(false);
            desktop.remove(this.th);
            this.th = null;
        }
        // Fecha Página Inicial
        if (this.th != null) {
            this.th.setVisible(false);
            desktop.remove(this.th);
            this.th = null;
        }
        // Fecha tela Produto
        if (this.tes != null) {
            this.tes.setVisible(false);
            desktop.remove(this.tes);
            this.tes = null;
        }

        // Fecha tela Caixa Vendas
        if (this.tcv != null) {
            this.tcv.setVisible(false);
            desktop.remove(this.tcv);
            this.tcv = null;
        }
        // Fecha Buscar nota
        if (this.bcn != null) {
            this.bcn.setVisible(false);
            desktop.remove(this.bcn);
            this.bcn = null;
        }

        // Fecha tela RH
        if (this.trh != null) {
            this.trh.setVisible(false);
            desktop.remove(this.trh);
            this.trh = null;
        }

        // Fecha tela Criar Login
        if (this.tcl != null) {
            this.tcl.setVisible(false);
            desktop.remove(this.tcl);
            this.tcl = null;
        }
        
        // Fecha tela sobre
        if (this.ts != null) {
            this.ts.setVisible(false);
            desktop.remove(this.ts);
            this.ts = null;
        }
        
        // Fecha tela Ajuda
        if (this.ta != null) {
            this.ta.setVisible(false);
            desktop.remove(this.ta);
            this.ta = null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private int cod_usuario = this.cod_usuario;

            public void run() {
                new TelaPrincipal(this.cod_usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem abrBusca;
    javax.swing.JMenuItem abrCriarLogin;
    javax.swing.JMenuItem abrMenCaixa;
    javax.swing.JMenuItem abrMenEstoque;
    javax.swing.JMenuItem abrMenSobre;
    javax.swing.JMenuItem abrRecHum;
    javax.swing.JMenuItem abrTrocarUsuario;
    javax.swing.JDesktopPane desktop;
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenuItem jMenuItem1;
    javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenu menCaixa;
    public javax.swing.JMenu menEstoque;
    javax.swing.JMenu menHome;
    javax.swing.JMenu menOpcoes;
    public javax.swing.JMenu menRelatorio;
    javax.swing.JMenuItem menRelatorioVenda;
    public javax.swing.JMenu menRh;
    javax.swing.JMenuItem menSair;
    javax.swing.JMenu menSobre;
    // End of variables declaration//GEN-END:variables
}
