/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viw;

import controle.Produto_controle;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Produto_modelo;

/**
 *
 * @author emesson
 */
public class TelaListaProdutos extends javax.swing.JInternalFrame {
    ArrayList<Produto_modelo> produtos = new ArrayList();

    /**
     * Creates new form TelaListaProdutos
     */
    public TelaListaProdutos() {
        initComponents();
        iniciarTabela();
    }
    
    // Inicia a tabela
    private void iniciarTabela() {
        DefaultTableModel dtmFuncionario = (DefaultTableModel) tabelaListaProdutos.getModel();

        // Retorna um arrayList de funcionarios
        this.produtos = new Produto_controle().buscarprodutos();

        for (int i = 0; i < this.produtos.size(); i++) {

            Object[] dadosProdutos = {
                produtos.get(i).getCod_produto(), 
                produtos.get(i).getNome(),
                produtos.get(i).getDescrição(),
                produtos.get(i).getValor_venda(),
                produtos.get(i).getQuantidade()             
            };
            
            dtmFuncionario.addRow(dadosProdutos);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaProdutos = new javax.swing.JTable();
        btnProdDeletar = new javax.swing.JButton();

        setTitle("Lista de produtos");

        tabelaListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod_produto", "Nome", "Descrição", "Valor_venda", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaListaProdutos);

        btnProdDeletar.setText("Deletar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProdDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdDeletar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdDeletar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaListaProdutos;
    // End of variables declaration//GEN-END:variables
}
